    # Generated by Django 5.0.1 on 2024-01-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmartPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('display_size', models.FloatField(blank=True, null=True)),
                ('storage_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('camera_resolution', models.PositiveIntegerField(blank=True, null=True)),
                ('battery_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('operating_system', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('is_water_resistant', models.BooleanField(default=False)),
                ('is_5g_enabled', models.BooleanField(default=False)),
                ('weight', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
